package com.evoltech.ciqapm.model;

public enum FaseConahcyt {
    INICIO,
    GENERACION_PROPUESTA,
    PROPUESTA_TERMINADA,
    SOLICITUD_AUTORIZACION_JEFE_DEPARTMENTO,
    SOLICITUD_AUTORIZACION_DIR_INVESTIGACION,
    SOLICITUD_AUTORIZACION_DIR_GRAL,
    SOLICITUD_CARTA_CIQA,
    ENVIAR_PROPUESTA_A_CONAHCYT,
    EN_ESPERA_RESPUESTA_CONAHCYT,
    RECEPCION_RESPUESTA_CONAHCYT,
    MANDAR_HIBERNACION,
    ACTIVACION_EJECUCION,
    EN_EJECUCION,
    TERMINADO,
    EN_CIERRE
}